/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://nwqyb3hue5gkdj5l45t7on2sum.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3nrs7smlezdrphoj4hmv6zvlry",
    "aws_cognito_identity_pool_id": "us-east-1:76af4bf5-aff3-4c45-8437-3c6880d13ec6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_wuNQr6FIj",
    "aws_user_pools_web_client_id": "5873tj7ba9nnfctv1fpvnqu4s8",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "PHONE_NUMBER"
    ],
    "aws_user_files_s3_bucket": "gateway9189b056d1a34c419355d6ada6e1b9d8184152-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
